### ISSUE TITLE
Here

### ISSUE THREAD

**Issue by ohto-ai** [genshin-lumine/Hello#3]
@XSSaGY

**Comment by XSSaGY** [comment]
you are my hero

**Comment by genshin-lumine** [comment]
学习去了

**Comment by ohto-ai** [comment]
嗯

**Comment by genshin-lumine** [comment]
我该怎么访问私有变量

**Comment by genshin-lumine** [comment]
还是说我根本就不应该设置成私有的？

**Comment by ohto-ai** [comment]
谁要访问私有变量，谁？对像自己，还是全局范围

**Comment by ohto-ai** [comment]
正常情况，全局范围不应该访问私有，对像应该提供访问方法

**Comment by genshin-lumine** [comment]
算是全局吧
另一个类里面的函数访问

**Comment by genshin-lumine** [comment]
是不是遵循谁的数据谁处理的原则？

**Comment by ohto-ai** [comment]
```cpp
class student
{
    public:
        void updateScore(double math, double chinese, double english) {
            mathScore_ = math;
            chineseScore_ = chinese;
            englishScore_ = english;
            totalScore_ = mathScore_ + chineseScore_ + englishScore_;
            aveageScore_ = totalScore_ / 3;
        }
        double aveageScore() const { return aveageScore_;}
        double totalScore() const { return totalScore_;}
        double mathScore() const { return mathScore_;}
        double chineseScore() const { return chineseScore_;}
        double englishScore() const { return englishScore_;}

    private:
        double mathScore_ {};
        double chineseScore_ {};
        double englishScore_ {};
        double aveageScore_ {};
        double totalScore_ {};
};
```

**Comment by ohto-ai** [comment]
建议这么写，更新分数和获取分数分开，提供公开的接口来访问就行

**Comment by genshin-lumine** [comment]
看懂是能看懂
但是有好多疑问
为什么要这么写
double mathScore_ {};
 这个是什么
double aveageScore() const { return aveageScore_;}
这个又是什么

**Comment by ohto-ai** [comment]
> 看懂是能看懂 但是有好多疑问 为什么要这么写 double mathScore_ {}; 这个是什么 double aveageScore() const { return aveageScore_;} 这个又是什么
1. double mathScore_ {}; 没啥好讲的，就是一个成员而已，提供了默认空值，防止有垃圾数据。
2. 这么写的原因，上面给出来了，要把读写操作分开，用公开接口访问，防止写入被无意中覆盖。
举个例子，你如果把average变量公开写入了，那么谁都可以修改他，这是不正确的，这个变量必须只有对像自己来更新。

**Comment by genshin-lumine** [comment]
那他是成员变量还是成员函数？

**Comment by ohto-ai** [comment]
变量

**Comment by genshin-lumine** [comment]
和mathScore=0没有区别吧

**Comment by ohto-ai** [comment]
嗯

**Comment by genshin-lumine** [comment]
我需要你的帮助 拿起你的手机

**Comment by ohto-ai** [comment]
图片发这里，我不方便看手机

**Comment by genshin-lumine** [comment]
明白

**Comment by genshin-lumine** [comment]
我要写个排序的函数 怎么实现呢
我现在的想法是找到任意一个成员然后让他和每一个成员比较
比它大就加1
这样我把所有都比较完之后我就可以得到一个序列

**Comment by ohto-ai** [comment]
你到底是要排序还是要给什么东西+1

**Comment by ohto-ai** [comment]
list有sort方法

**Comment by genshin-lumine** [comment]
加一

**Comment by ohto-ai** [comment]
你也可以使用自定义的comp来排序

**Comment by ohto-ai** [comment]
给谁+1

**Comment by ohto-ai** [comment]
我不清楚你为什么排序的同时还要+1，这个需求很奇怪

**Comment by genshin-lumine** [comment]
给名次加一啊

**Comment by genshin-lumine** [comment]
并不一定要排序

**Comment by ohto-ai** [comment]
名次这个东西不应该属于学生的结构体里面

**Comment by ohto-ai** [comment]
因为单独一个学生是不存在名次的，必须要有班级这个整体才能有名次

**Comment by ohto-ai** [comment]
所以你不要加rank这种成员，

**Comment by genshin-lumine** [comment]
那你的意思是我要再加别的类？

**Comment by ohto-ai** [comment]
我推荐的是在视图里显示名次就可以了，或者你加个view的list

**Comment by ohto-ai** [comment]
嗯，可以这么做

**Comment by ohto-ai** [comment]
yq如果让你把名次加进结构体里面，那就是她代码写少了

**Comment by genshin-lumine** [comment]
在视图里显示名次就可以了，或者你加个view的lis
这是什么意思
怎么实现

**Comment by ohto-ai** [comment]
最简单的，你可以根据分数来排序这些元素的iter，显示的时候显示就可以了

**Comment by genshin-lumine** [comment]
？

**Comment by genshin-lumine** [comment]
C++函数调用的时候怎么缺省啊

**Comment by ohto-ai** [comment]
给个默认值就行

**Comment by genshin-lumine** [comment]
![Q14%RJE@FAKDKA0NK`746{F](https://user-images.githubusercontent.com/50444548/236779576-2fd3f658-8728-4702-ac30-fc8621100e82.png)

**Comment by genshin-lumine** [comment]
我怎么通过这个p访问类里面的成员函数啊

**Comment by ohto-ai** [comment]
> 最简单的，你可以根据分数来排序这些元素的iter，显示的时候显示就可以了

```cpp
#include <list>
#include <iostream>

template <typename ItemType = int>
class ListView: protected std::list<std::list<ItemType>::const_iterator>
{
public:
    template <typename Compare>
    void update(const std::list<ItemType>& items, Compare comp)
    {
        clear();
        for(auto it = items.cbegin(); it != items.cend(); it++)
            push_back(it);
        sort([comp](const auto&a, const auto&b){ return comp(*a, *b); });
    }

    void update(const std::list<ItemType>& items)
    {
        clear();
        for(auto it = items.cbegin(); it != items.cend(); it++)
            push_back(it);
        sort();
    }

    using std::list<std::list<ItemType>::const_iterator>::cbegin;
    using std::list<std::list<ItemType>::const_iterator>::begin;
    using std::list<std::list<ItemType>::const_iterator>::cend;
    using std::list<std::list<ItemType>::const_iterator>::end;
};

int main()
{
    std::list<int> list {1,3,5,7,7,5,5,1,3,2};
    ListView<int> view;
    view.assign(list);
    for(auto ref: list)
    {
        std::cout<< *ref << std::endl;
    }

    return 0;
}
```
这个代码是手写的，没调试过，应该有一堆错误，你可以看着调整下

**Comment by ohto-ai** [comment]
> ![Q14%RJE@FAKDKA0NK`746{F](https://user-images.githubusercontent.com/50444548/236779576-2fd3f658-8728-4702-ac30-fc8621100e82.png)

你为什么要定义p

**Comment by ohto-ai** [comment]
算了，你先看书吧，晚上我和你讲讲

**Comment by ohto-ai** [comment]
先看看stl基础

**Comment by genshin-lumine** [comment]
为了遍历一遍这个list啊

**Comment by ohto-ai** [comment]
> 为了遍历一遍这个list啊

我不是给你例子了吗，你怎么写成这样了

**Comment by genshin-lumine** [comment]
#include <list>
#include <iostream>

template <typename ItemType = int>
class ListView: protected std::list<std::list<ItemType>::const_iterator>
{
public:
    template <typename Compare>
    void update(const std::list<ItemType>& items, Compare comp)
    {
        clear();
        for(auto it = items.cbegin(); it != items.cend(); it++)
            push_back(it);
        sort([comp](const auto&a, const auto&b){ return comp(*a, *b); });
    }

    void update(const std::list<ItemType>& items)
    {
        clear();
        for(auto it = items.cbegin(); it != items.cend(); it++)
            push_back(it);
        sort();
    }

    using std::list<std::list<ItemType>::const_iterator>::cbegin;
    using std::list<std::list<ItemType>::const_iterator>::begin;
    using std::list<std::list<ItemType>::const_iterator>::cend;
    using std::list<std::list<ItemType>::const_iterator>::end;
};

int main()
{
    std::list<int> list {1,3,5,7,7,5,5,1,3,2};
    ListView<int> view;
    view.assign(list);
    for(auto ref: list)
    {
        std::cout<< *ref << std::endl;
    }

    return 0;
}
这例子我才看
一直被墙

**Comment by ohto-ai** [comment]
```cpp
for(auto& stu: students)
{
    std::cout << stu.name() << "\t" << stu.totalScore() << std::endl;
}
```
比如这个，打印每个人的总分

**Comment by ohto-ai** [comment]
不是上面很长的例子，是我qq上发过你的

**Comment by genshin-lumine** [comment]
那个我写出来了

**Comment by genshin-lumine** [comment]
但是我不明白里面参数的意思
再画瓢就画不出来了

**Comment by genshin-lumine** [comment]
![image](https://user-images.githubusercontent.com/50444548/236783754-fce172ad-5aff-4fa4-b11f-920fdf655525.png)
我以为他这个*p是指向表中的具体元素的

**Comment by genshin-lumine** [comment]
你写的这个我看不懂
头大

**Comment by genshin-lumine** [comment]
大概意思是不是让我创立一个新的表 然后遍历一遍原来的表
原来表排好序的话就复制到新的表里？

**Comment by ohto-ai** [comment]
> 大概意思是不是让我创立一个新的表 然后遍历一遍原来的表 原来表排好序的话就复制到新的表里？

不是，复制整张表很耗时，所以我拷贝的迭代器

**Comment by ohto-ai** [comment]
拷贝迭代器才叫做view
